target: Income

perturbations: 
  - name: [Age, EducationNum]
    type: integer
    size: 3
  - name: fnlwgt
    type: integer
    size: 100
  - name: [CapitalGain, CapitalLoss]
    type: integer
    size: 100
    frozen_values: [0]
  - name: HoursPerWeek
    type: swap
    size: 3

transform: 
  - name: [CapitalGain, CapitalLoss]
    type: add_normal_noise_and_round
    noise_std: 10
    digits: 2
    frozen_values: [0]

rename:
  Age: Age
  WorkClass: Employment
  fnlwgt: Census Weight
  Education: Highest Education
  EducationNum: Education as number
  MaritalStatus: Relationship
  Occupation: Work
  Relationship: Relationship
  Race: Self-reported race
  Gender: Self-reported gender
  CapitalGain: Investement Income
  CapitalLoss: Investment Loss
  HoursPerWeek: Hours worked
  NativeCountry: Country of origin
  Income: Yearly Income

recode:
  WorkClass:
    Private: Private Sector
    Self-emp-not-inc: Self-employed and not incorporated
    Self-emp-inc: Self-employed and incorporated
    Federal-gov: Federal government employee
    Local-gov: Local government
    State-gov: State government
    Without-pay: Working, but without pay
    Never-worked: Has never been employed
  Education:
    Preschool: Preschool
    1st-4th: 1st to 4th grade
    5th-6th: 5th to 6th grade
    7th-8th: 7th to 8th grade
    9th: 9th grade
    10th: 10th grade
    11th: 11th grade
    12th: 12th grade
    HS-grad: High School Graduate
    Some-college: Went to college, but did not graduate
    Assoc-voc: Associate degree in vocational studies
    Assoc-acdm: Associate degree in academic studies
    Bachelors: Bachelor's degree
    Masters: Master's degree
    Prof-school: Professional degree beyond bachelor's
    Doctorate: Doctorate
  MaritalStatus:
    Married-civ-spouse: Married, civilian spouse
    Divorced: Divorced
    Never-married: Never married
    Separated: Legally married but living separately
    Widowed: Widowed
    Married-spouse-absent: Married, but spouse is absent
    Married-AF-spouse: Married to an armed forces member
  Occupation:
    Tech-support: Technical support role
    Craft-repair: Craft or repair role
    Other-service: Service role
    Sales: Sales
    Exec-managerial: Executive, managerial, or otherwise supervisory role
    Prof-specialty: Professional with specialized knowledge
    Handlers-cleaners: Handlers and cleaners
    Machine-op-inspct: Machine operator inspector
    Adm-clerical: Administrative clerical
    Farming-fishing: Farming and fishing
    Transport-moving: Transport moving
    Priv-house-serv: Private house service
    Protective-serv: Protective service
    Armed-Forces: Armed forces
  Relationship:
    Wife: Wife
    Own-child: Child in the family
    Husband: Husband
    Not-in-family: Not in family
    Other-relative: Another relative of the family
    Unmarried: Unmarried
  Race:
    White: White
    Asian-Pac-Islander: Asian Pacific Islander
    Amer-Indian-Eskimo: American Indian Eskimo
    Other: Other
  Gender:
    Male: Male
    Femae: Female
  NativeCountry:
    United-States: United States
    Cambodia: Cambodia
    England: England
    Puerto-Rico: Puerto Rico
    Canada: Canada
    Germany: Germany
    Outlying-US(Guam-USVI-etc): Outlying US
    India: India
    Japan: Japan
    Greece: Greece
    South: South
    China: China
    Cuba: Cuba
    Iran: Iran
    Honduras: Honduras
    Philippines: Philippines
    Italy: Italy
    Poland: Poland
    Jamaica: Jamaica
    Vietnam: Vietnam
    Mexico: Mexico
    Portugal: Portugal
    Ireland: Ireland
    France: France
    Dominican-Republic: Dominican Republic
    Laos: Laos
    Ecuador: Ecuador
    Taiwan: Taiwan
    Haiti: Haiti
    Columbia: Columbia
    Hungary: Hungary
    Guatemala: Guatemala
    Nicaragua: Nicaragua
    Scotland: Scotland
    Thailand: Thailand
    Yugoslavia: Yugoslavia
    El-Salvador: El Salvador
    Trinadad&Tobago: Trinidad and Tobago
    Peru: Peru
    Hong: Hong
    Holand-Netherlands: Netherlands
  Income:
    <=50K: Less than 50K
    ">50K": More than 50K